### ISSUE TITLE
unable to get it working

### ISSUE THREAD

**Issue by vyorkin** [okaxaki/pegjs-backtrace#1]
steps:

* define any simple grammar that contains error
* create a new parser using JavaScript API: `peg.generate(grammar, { trace: true })`

```
import peg from 'pegjs';
import Tracer from 'pegjs-backtrace';

export default function run() {
  const grammar = `
    expr = term ([-+] term)*
    term = factor ([*/] factor)*
    factor = '(' expr ')' / number
    nmber = digits:[0-9]+ { return digits.join(''); }
  `;
  //  ^-- example error ("nmber")

  const text = '1+10';
  const tracer = new Tracer(text);

  try {
    const parser = peg.generate(grammar, { trace: true });
    const result = parser.parse(text, { tracer });

    console.log('result: ', result);
  } catch (err) {
    console.log('error: ', err);
    console.log(tracer.getBacktraceString());
  }
}
```

but this works:

```
import peg from 'pegjs';

export default function run() {
  const grammar = `
    expr = term ([-+] term)*
    term = factor ([*/] factor)*
    factor = '(' expr ')' / number
    nmber = digits:[0-9]+ { return digits.join(''); }
  `;
  const parser = peg.generate(grammar, { trace: true });
  const result = parser.parse('1+10', {
    tracer: {
      trace: function (evt) {
        console.log(evt);
      },
    },
  });
}
```

here is an example repo demonstrating the problem: https://github.com/vyorkin-play/pegjs-trace-issue.

could you please point out my mistake? what am I doing wrong here? thank you!

**Comment by okaxaki** [comment]
Hi, pegjs-backtrace is a tool for analyzing syntax error in the parser's input text, not for the grammer itself. Both examples seem to throw the exception in `peg.generate`.

I have checked your arithmetic.js and obtained the following exception. This comes from `peg.generate`.

> bundle.js:2627 error:  GrammarError {name: "GrammarError", message: "Rule "number" is not defined.", location: Object, stack: "GrammarError: Rule "number" is not defined.↵    at….each (http://localhost:8080/dist/bundle.js:67:7)"}

**Comment by vyorkin** [comment]
oh, got it! ありがとう!

**Comment by vyorkin** [comment]
hey @okaxaki !
here is an updated example:
https://github.com/vyorkin-play/pegjs-trace-issue/blob/master/src/arithmetics-backtrace-generated.js#L19

I've generated a new parser with `pegjs` CLI using grammar rules from [grammars/arithmetics.pegjs](https://github.com/vyorkin-play/pegjs-trace-issue/blob/master/src/grammars/arithmetics.pegjs) by running this command:
```
~/projects/play/pegjs/hello/src/generated-parsers master*
❯ pegjs --trace -o arithmetics-parser.js ../grammars/arithmetics.pegjs
```

for some reason it still says that backtrace isn't found, even though I've generated the parser with `---trace` key:

```
error:  peg$SyntaxError {message: "Expected [*/], [0-9], [\-+], or end of input but " " found.", expected: Array[4], found: " ", location: Object, name: "SyntaxError"…}

bundle.js:1562 No backtrace found. Make sure you use `pegjs --trace` to build your parser javascript.
Or, the failure might occur in the start node.
```

but it works if I change input to be:
```
  const text = '1+a'; // <-- example error
```

^ given the input I've mentioned above `getBacktraceString()` produces the following output:

```
x 1:3-1:3 number
| 1+a
|   ^
x 1:3-1:3 factor
| 1+a
|   ^
x 1:3-1:3 term
| 1+a
|   ^
o 1:1-1:2 expr
  1+a
  ^
```
which is good

**Comment by okaxaki** [comment]
Hi,

Sorry that the current pegjs-backtrace does not output the backtrace if the error occurs in the start node.

For the input text `1+10 a b`, the parser consumes `1+10` as `term + term`, and then rejects the succeeding `a` in the context of `expr` - the start node of arithmetics.pegjs.

However, in such case, the error information is unhelpful so I will consider on more intuitive message as future improvement.

**Comment by vyorkin** [comment]
I'll leave this open then. thanks again!
