### ISSUE TITLE
tree view for regular successful parses?

### ISSUE THREAD

**Issue by localhostdotdev** [okaxaki/pegjs-backtrace#3]
like what happens for errors, i'm not sure if this is possible

----

(actually mostly wanted to say thank you, this is quite an amazing thing you made!)

**Comment by okaxaki** [comment]
Hi, it is possible by using `getParseTreeString()` instead of `getBacktraceString()`.
https://github.com/okaxaki/pegjs-backtrace/blob/master/test/index.js

**Comment by localhostdotdev** [comment]
omg should have looked at the source, thanks a lot it works really well, I may need to change a few things to not get a giant graph though :) (probably with `hiddenPaths`)
